name: Lints

on: [push]

jobs:
  lints:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install NPM Dependencies
        run: npm ci
      - name: Install Foundry Modules
        run: npm run install
      - name: Run lints
        run: npm run format
